set(CNIAI_CUDA_KERNEL_HEADERS_DIR "${CMAKE_CURRENT_LIST_DIR}/../include")

file(GLOB CNIAI_CUDA_KERNEL_TOP_HEADERS "${CNIAI_CUDA_KERNEL_HEADERS_DIR}/cniai_cuda_kernel/*.h")
set(CNIAI_CUDA_KERNEL_ALL_HEADERS ${CNIAI_CUDA_KERNEL_TOP_HEADERS})

source_group("Header Files\\cniai_cuda_kernel" FILES ${CNIAI_CUDA_KERNEL_TOP_HEADERS})