function(cniai_cuda_kernel_extract_version)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/include/cniai_cuda_kernel/version.h" file_contents)
    string(REGEX MATCH "CNIAI_CUDA_KERNEL_VER_MAJOR ([0-9]+)" _ "${file_contents}")
    if(NOT CMAKE_MATCH_COUNT EQUAL 1)
        message(FATAL_ERROR "Could not extract major version number from cniai_cuda_kernel/version.h")
    endif()
    set(ver_major ${CMAKE_MATCH_1})

    string(REGEX MATCH "CNIAI_CUDA_KERNEL_VER_MINOR ([0-9]+)" _ "${file_contents}")
    if(NOT CMAKE_MATCH_COUNT EQUAL 1)
        message(FATAL_ERROR "Could not extract minor version number from cniai_cuda_kernel/version.h")
    endif()

    set(ver_minor ${CMAKE_MATCH_1})
    string(REGEX MATCH "CNIAI_CUDA_KERNEL_VER_PATCH ([0-9]+)" _ "${file_contents}")
    if(NOT CMAKE_MATCH_COUNT EQUAL 1)
        message(FATAL_ERROR "Could not extract patch version number from cniai_cuda_kernel/version.h")
    endif()
    set(ver_patch ${CMAKE_MATCH_1})

    set(CNIAI_CUDA_KERNEL_VERSION_MAJOR ${ver_major} PARENT_SCOPE)
    set(CNIAI_CUDA_KERNEL_VERSION_MINOR ${ver_minor} PARENT_SCOPE)
    set(CNIAI_CUDA_KERNEL_VERSION_PATCH ${ver_patch} PARENT_SCOPE)
    set(CNIAI_CUDA_KERNEL_VERSION "${ver_major}.${ver_minor}.${ver_patch}" PARENT_SCOPE)
endfunction()