#!/usr/bin/env bash

set -e

SCRIPT_PATH=$(readlink -f "$0")
CNIAI_CUDA_KERNEL_SOURCE_DIR=$(dirname "$SCRIPT_PATH")

CNIAI_INSTALL_PATH="${CNIAI_CUDA_KERNEL_SOURCE_DIR}/../install"

CNIAI_CUDA_KERNEL_BUILD_DIR="${CNIAI_CUDA_KERNEL_SOURCE_DIR}/build"

rm -rf "${CNIAI_CUDA_KERNEL_BUILD_DIR}" && mkdir -p "${CNIAI_CUDA_KERNEL_BUILD_DIR}" && cd "${CNIAI_CUDA_KERNEL_BUILD_DIR}"
cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX="${CNIAI_INSTALL_PATH}" "${CNIAI_CUDA_KERNEL_SOURCE_DIR}"
make -j $(($(nproc) + 1)) && make install